parameters:
#    proyecto_user.example.class: Proyecto\UserBundle\Example

services:
#    proyecto_user.example:
#        class: %proyecto_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
